baseURL = "https://longhorn.ms/"
languageCode = "en-us"
title = "Experience Longhorn"
theme = "ananke"
Paginate = 12
SectionPagesMenu = "main"
enableGitInfo = true
enableRobotsTXT = true

[params]
description = "A look at a defining Microsoft project"
gitlab = "https://gitlab.com/experience-longhorn/longhorn-ms"
featured_image = "/images/header-01.jpg"
custom_css = [ "dist/custom.css" ]
mainSections = [ "articles" ]

[taxonomies]
category = "categories"

[blackfriday]
hrefTargetBlank = true

[imaging]
resampleFilter = "CatmullRom"
quality = 80